### ISSUE TITLE
Create the Editor

### ISSUE THREAD

**Issue by OlivierJM** [brianmuks/lubuto-library#10]
List of the necessary components, these will be on the dashboard

- [ ] Main Editor
- [x] Tool Editor(Resource)
- [ ] Added Tools

**Comment by OlivierJM** [comment]
I have managed to share the states between components using context and hooks, it looks cool it took me time to get there but it is working, we now need to properly arrange them.

**Comment by brianmuks** [comment]
What has been done :https://drive.google.com/file/d/1cxEVArSXcELNbI80jmZUwo8UGEof7Q0P/view?usp=drivesdk
