### ISSUE TITLE
landing page

### ISSUE THREAD

**Issue by OlivierJM** [brianmuks/lubuto-library#15]
Add a basic landing page to show progress to the Lubuto, we can deploy it so that they see something moving.

**Comment by brianmuks** [comment]
Lets write to them and promise an update this Friday. We need to make sure that we have more than what we presented. In the mean time you can deploy as we push code so that we can both have a feel of the system.

**Comment by OlivierJM** [comment]
Alright Brian, I will do that.

**Comment by OlivierJM** [comment]
I deployed.
